version: '3'
services:
  rails:
    tty: true
    build:
      context: ./
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - '3000:3000'
      # http://localhost:3000
    working_dir: /app
    volumes:
      - '.:/app/'
    environment:
      RAILS_ENV: 'development'
    depends_on:
      # - mysql
      - postgres

  # mysql:
  #   image: 'mysql:8.0'
  #   ports:
  #     - '${DB_PORT}:3306'
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #     MYSQL_TCP_PORT: ${DB_PORT}
  #   expose:
  #     - '${DB_PORT}:3306'
  #   volumes:
  #     - 'app_volumes:/var/lib/mysql'
  #     - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: demo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # http://localhost:8080
    # user: postgres
    # pass: example

volumes:
  app_volumes:
    driver: local
